# Generated by Django 3.1 on 2020-09-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articles',
            fields=[
                ('titre', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('icon', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now=True)),
                ('contenue', models.TextField(default='')),
                ('titre_block_1', models.CharField(max_length=255)),
                ('image_block_1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('block_1', models.TextField(default='')),
                ('titre_block_2', models.CharField(max_length=255)),
                ('image_block_2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('block_2', models.TextField(default='')),
                ('titre_block_3', models.CharField(max_length=255)),
                ('image_block_3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('block_3', models.TextField(default='')),
            ],
        ),
    ]
