# Generated by Django 3.1 on 2020-09-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='block_1',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='block_2',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='block_3',
            field=models.TextField(default='', null=True),
        ),
    ]
