# Generated by Django 3.1 on 2020-09-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200904_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='block_4',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='image_block_4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='articles',
            name='titre_block_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='block_1',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='block_2',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='block_3',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='titre_block_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='titre_block_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
