# Generated by Django 3.1 on 2020-09-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200904_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='block_5',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='block_6',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='image_block_5',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='articles',
            name='image_block_6',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='articles',
            name='titre_block_5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='titre_block_6',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
